-- ============================================================
-- QUIZ QUESTIONS: Certificate 3 Final Exam + Certificate 4
-- Run this in Supabase SQL Editor
-- ============================================================

-- Building Your First AI Application
INSERT INTO quiz_questions (course_id, module_id, question, options, correct, position) VALUES
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','What is the primary purpose of an API key when building AI applications?','["To style the user interface","To authenticate requests to the AI service","To store user data","To compress response data"]',1,1),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','Which format is most commonly used to send and receive data from AI APIs?','["XML","CSV","JSON","HTML"]',2,2),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','What does temperature control in an AI model?','["Processing speed","Randomness and creativity of the output","Maximum response length","The language of the output"]',1,3),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','What is a token in the context of AI language models?','["A security credential","A unit of text the model processes","A database record","A CSS class"]',1,4),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','What is the purpose of a system prompt?','["To style the chat interface","To set instructions and context for the AI behaviour","To store conversation history","To manage API rate limits"]',1,5),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','What does streaming mean in AI API responses?','["Playing audio","Sending responses word by word as generated","Compressing the response","Caching previous responses"]',1,6),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','Why should you never expose your AI API key in client-side code?','["It slows the app","Anyone could use it and incur costs on your account","It causes CSS errors","It breaks API calls"]',1,7),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','What is a context window in AI models?','["The visual chat area","The maximum amount of text a model can process at once","The browser window size","The API timeout"]',1,8),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','What is the best practice for handling AI API errors?','["Crash immediately","Ignore all errors","Implement retry logic with user-friendly error messages","Only show errors to developers"]',2,9),
('a059a78a-767c-4b35-a0ee-07fde5fa87a4','ai-app-m13','Which describes a multi-turn conversation in AI applications?','["One question with one answer","A conversation that maintains message history across multiple exchanges","A database transaction","A streaming response"]',1,10);

-- Introduction to AI Agents
INSERT INTO quiz_questions (course_id, module_id, question, options, correct, position) VALUES
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What is an AI agent?','["A human who manages AI","An AI system that takes actions autonomously to achieve goals","A type of database","A UI component"]',1,1),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What is a tool in the context of AI agents?','["A physical device","A function the agent calls to perform actions like web search or code execution","A neural network layer","A UI element"]',1,2),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What is the ReAct pattern in AI agents?','["A CSS framework","Agents alternate between reasoning and taking actions","A database query pattern","A testing methodology"]',1,3),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What is memory in an AI agent system?','["GPU RAM","The ability to store and retrieve information across interactions","Training data","The API rate limit cache"]',1,4),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What is tool calling (function calling)?','["Calling phone numbers","The AI model requesting execution of specific functions","Running Python directly","Sending emails"]',1,5),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What is an orchestrator in a multi-agent system?','["A music player","The agent that coordinates and directs other agents","A database manager","A CSS preprocessor"]',1,6),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What problem does agent memory solve?','["Slow processing","LLMs are stateless and forget previous interactions","High API costs","Poor code quality"]',1,7),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','Which risk is specific to AI agents vs basic chatbots?','["They use more tokens","Agents take real-world actions that may be hard to reverse","They need more RAM","They are slower"]',1,8),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What is grounding in AI agents?','["Electrical safety","Connecting agent responses to verified real-world data","A training technique","A UI principle"]',1,9),
('ebe19f19-87af-472b-a857-b421dde5d685','ai-agents-m14','What does a multi-agent system consist of?','["Multiple users with one AI","Multiple AI agents working together","Multiple databases","Multiple API keys"]',1,10);

-- Introduction to RAG Systems
INSERT INTO quiz_questions (course_id, module_id, question, options, correct, position) VALUES
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What does RAG stand for?','["Random Aggregation Generator","Retrieval-Augmented Generation","Recursive Agent Graph","Relational AI Generator"]',1,1),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What problem does RAG primarily solve?','["Slow inference","Knowledge cut-off dates and hallucinations about specific documents","High GPU costs","Poor code generation"]',1,2),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What is a vector embedding?','["An image format","A numerical representation of text that captures its meaning","A database join","A compression algorithm"]',1,3),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What is a vector database used for in RAG?','["Storing images","Storing and searching embeddings by semantic similarity","Running SQL queries","Managing user sessions"]',1,4),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What is chunking in RAG systems?','["Compressing video","Breaking large documents into smaller pieces for embedding","Deleting old data","Formatting responses"]',1,5),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','In a RAG pipeline, what happens after documents are retrieved?','["They are deleted","They are sent to the AI as context along with the user question","They are emailed","They are translated"]',1,6),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What is cosine similarity used for in RAG?','["Calculating angles","Measuring how similar two vector embeddings are","Compressing files","Building networks"]',1,7),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','Why is chunk size important in RAG?','["It affects file size","Too large wastes context window; too small loses meaning","It sets API cost","It controls font size"]',1,8),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What is re-ranking in advanced RAG?','["Sorting tables","A second pass that reorders retrieved chunks by relevance","A training technique","A UI animation"]',1,9),
('d9b80b63-c2a2-45fc-b12f-e596d771400e','rag-systems-m15','What makes RAG better than fine-tuning for frequently updated information?','["RAG is cheaper","RAG retrieves live data without retraining the model","RAG uses less memory","RAG is faster to build"]',1,10);

-- Professional Developer Skills
INSERT INTO quiz_questions (course_id, module_id, question, options, correct, position) VALUES
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What is the purpose of code review?','["To slow development","To catch bugs, improve quality, and share knowledge","To show off skills","To increase commits"]',1,1),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What does version control with Git allow?','["Control UI design","Track changes, collaborate safely, and revert to previous states","Manage databases only","Control API versions"]',1,2),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What is a pull request?','["A download request","A proposal to merge changes into the main codebase for review","A database backup","A server restart"]',1,3),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What does CI/CD stand for?','["Code Inspection / Code Delivery","Continuous Integration / Continuous Deployment","Client Interface / Client Design","Central Index / Central Database"]',1,4),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What is an environment variable used for?','["Storing CSS colours","Storing config values like API keys separately from code","Defining schemas","Setting font sizes"]',1,5),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What does it mean to write clean code?','["Code with no comments","Code that is readable, organised, and easy to maintain","Code using the latest framework","Code with fewest lines"]',1,6),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What is the main benefit of linting tools?','["Faster code execution","Automatically catch style issues and potential bugs before production","Generate documentation","Compress code"]',1,7),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What is the purpose of writing a README file?','["List every line of code","Explain what the project does, how to set it up, and how to use it","Store API keys","Define CSS styles"]',1,8),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What is technical debt?','["Money owed to cloud providers","Cost of shortcuts in development that will need fixing later","Number of open bugs","Time spent on docs"]',1,9),
('a658d1d1-fa7e-40ca-955d-2863b86644ce','pro-dev-skills-m16','What is the purpose of a staging environment?','["To showcase the product","To test changes in a production-like environment before going live","To train developers","To store backups"]',1,10);

-- Industry Capstone Project
INSERT INTO quiz_questions (course_id, module_id, question, options, correct, position) VALUES
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','When presenting a technical project to non-technical stakeholders, what should you focus on?','["Every line of code","The business value and problem it solves","The number of files","The programming language"]',1,1),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What is the first step before deploying to production?','["Adding more features","Testing in a staging environment that mirrors production","Deleting the dev database","Removing comments"]',1,2),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What does MVP stand for in software development?','["Most Valuable Player","Minimum Viable Product","Maximum Value Proposition","Multiple Version Protocol"]',1,3),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What is monitoring in production?','["Watching users on webcam","Tracking errors, performance, and usage to catch issues proactively","Reviewing code","Testing features"]',1,4),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What should a capstone project portfolio piece include?','["Only the code","Problem solved, approach, tech stack, challenges, and results","Just UI screenshots","Only the README"]',1,5),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What is a deployment pipeline?','["A water pipe in a server room","An automated process that tests and deploys code to production","A project timeline","A networking protocol"]',1,6),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What practice helps an application handle more users as it grows?','["Using more UI colours","Designing for scalability from the start","Longer variable names","More comments"]',1,7),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What is user feedback used for in product development?','["Finding spelling mistakes","Understanding real user needs and improving based on actual usage","Testing performance","Generating marketing content"]',1,8),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What does version control help with in a team project?','["UI design decisions","Preventing code conflicts, tracking history, and enabling safe collaboration","Database management","API documentation"]',1,9),
('2039b1e7-7313-4e50-97ec-fdd4dedf7cf7','capstone-m17','What is the key difference between a project demo and production deployment?','["There is no difference","A demo shows functionality; production must be stable, secure, and scalable","Demos use real data","Production has no UI"]',1,10);

-- Certificate 3 Final Exam (Prompt Engineering + Testing + Documentation)
INSERT INTO quiz_questions (course_id, module_id, question, options, correct, position) VALUES
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is prompt engineering?','["Writing code prompts","Crafting effective inputs to get desired outputs from AI models","A hardware design process","A database query language"]',1,1),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is a zero-shot prompt?','["An empty prompt","Asking the model to perform a task with no examples provided","A prompt with many examples","A failed API call"]',1,2),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is few-shot prompting?','["Using a small model","Providing a few examples in the prompt to guide the model","Limiting the response length","Reducing API calls"]',1,3),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is chain-of-thought prompting?','["Linking prompts together","Asking the model to show its reasoning step-by-step before answering","A multi-user system","A caching technique"]',1,4),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is prompt injection?','["Adding variables to prompts","A security attack where malicious input overrides the intended prompt instructions","Inserting code into a database","A formatting technique"]',1,5),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What does unit testing verify?','["The entire application","Individual functions or components in isolation","The database schema","The UI design"]',1,6),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is the purpose of integration testing?','["Testing one function","Testing how multiple components work together","Testing the UI only","Testing API keys"]',1,7),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What does TDD stand for?','["Technical Design Document","Test-Driven Development","Total Data Dependency","Tool-Driven Deployment"]',1,8),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is a test coverage percentage?','["User satisfaction score","The proportion of code executed during automated tests","API response rate","Documentation completeness"]',1,9),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is the main purpose of technical documentation?','["Marketing the product","Helping developers understand, use, and maintain code systems","Storing passwords","Styling the application"]',1,10),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What should an API documentation include?','["Only the server code","Endpoint descriptions, request/response formats, and usage examples","Only error codes","The development timeline"]',1,11),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is a docstring?','["A string with errors","An inline comment explaining what a function does, its parameters and return value","A database string type","A UI label"]',1,12),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','Which technique helps AI produce more consistent outputs?','["Random temperature","Adding role instructions and output format constraints to the prompt","Shorter prompts always","Removing context"]',1,13),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is regression testing?','["Testing only new features","Re-running existing tests to ensure changes did not break previous functionality","Testing on older hardware","Performance benchmarking"]',1,14),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What makes good technical communication to a non-technical audience?','["Using as many acronyms as possible","Explaining concepts clearly without jargon, focusing on outcomes and value","Sharing full code listings","Avoiding all technical detail"]',1,15),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is a mock in software testing?','["A fake user","A simulated version of a dependency used to isolate the code being tested","A UI prototype","A staging server"]',1,16),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is the role attribute used for in prompts?','["Setting HTML roles","Telling the AI to behave as a specific persona or expert","Defining database roles","Setting access permissions"]',1,17),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What does end-to-end testing verify?','["One function only","The complete user flow from start to finish as a real user would experience it","The backend API only","The database schema"]',1,18),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','What is a changelog in software documentation?','["A log of errors","A record of all changes made between software versions","A list of all functions","A deployment script"]',1,19),
('49401711-5365-420d-96d3-e937115bd330','cert3-final-exam','Which is a sign of a well-engineered prompt for a coding assistant?','["It is as short as possible","It specifies the language, task, constraints, and expected output format clearly","It uses no punctuation","It has no examples"]',1,20);

-- Certificate 4 Final Exam (AI Apps + Agents + RAG + Pro Skills + Capstone)
INSERT INTO quiz_questions (course_id, module_id, question, options, correct, position) VALUES
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is the primary role of an API key in an AI application?','["Styling the UI","Authenticating requests to the AI service","Compressing responses","Storing user data"]',1,1),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What does a higher temperature setting do to AI model outputs?','["Makes responses faster","Makes responses more random and creative","Makes responses shorter","Makes responses more factual"]',1,1),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is the context window of an AI model?','["The UI display area","The maximum amount of text the model can process at one time","The browser window","The API timeout limit"]',1,3),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What makes AI agents different from basic chatbots?','["Agents use more tokens","Agents can take real-world actions using tools","Agents are slower","Agents cost less"]',1,4),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is the ReAct pattern?','["A React.js framework","Agents reason about a problem then take an action, repeating until done","A REST API pattern","A testing methodology"]',1,5),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What does RAG stand for?','["Random Aggregation Generator","Retrieval-Augmented Generation","Recursive Agent Graph","Relational AI Generator"]',1,6),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is chunking in a RAG pipeline?','["Compressing files","Breaking documents into smaller pieces for embedding","Deleting old vectors","Formatting model output"]',1,7),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is a vector database used for?','["Storing images","Storing and searching embeddings by semantic similarity","Running SQL joins","Managing auth sessions"]',1,8),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','Why should API keys never be in client-side code?','["It slows the app","Anyone can steal and use them at your expense","It causes type errors","It breaks routing"]',1,9),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is tool calling in the context of AI agents?','["Calling phone numbers","The model requesting a specific function be executed on its behalf","Running SQL directly","Sending emails from code"]',1,10),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is an orchestrator agent?','["A music streaming agent","An agent that manages and coordinates other agents","A database admin","A CSS tool"]',1,11),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What problem does RAG solve that fine-tuning does not?','["RAG is cheaper","RAG can access up-to-date information without retraining the model","RAG uses less memory","RAG responds faster"]',1,12),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is cosine similarity used for in RAG?','["Calculating geometry","Measuring how semantically similar two text embeddings are","Sorting database rows","Building UI grids"]',1,13),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is CI/CD?','["Code Inspection / Code Delivery","Continuous Integration / Continuous Deployment","Client Interface / Client Design","Central Index / Database"]',1,14),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is technical debt?','["Cloud hosting costs","The long-term cost of shortcuts taken during development","Number of open bugs","Licensing fees"]',1,15),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What does a pull request allow in a team?','["Downloading the project","Reviewing and discussing code changes before merging into the main branch","Resetting the database","Deploying to production"]',1,16),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is an MVP?','["Most Valuable Player","Minimum Viable Product — a basic version to test with real users","Maximum Value Proposition","Multiple Version Protocol"]',1,17),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is production monitoring?','["Filming a factory","Tracking errors, performance, and uptime in a live application","Code reviewing","UI testing"]',1,18),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','When presenting a capstone project, what should you lead with?','["All the code","The problem it solves and the value it delivers","The number of commits","The framework used"]',1,19),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is agent memory used for?','["RAM management","Persisting information across sessions so the agent remembers past interactions","Caching API responses","Storing CSS variables"]',1,20),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is grounding in AI systems?','["Electrical safety","Connecting AI outputs to verified, real-world factual information","A training technique","A UI design pattern"]',1,21),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is re-ranking in an advanced RAG system?','["Sorting search results by date","A second pass that reorders retrieved chunks by relevance before passing to the model","A retraining step","An API retry"]',1,22),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What does scalability mean in application development?','["Using large fonts","The ability to handle growing users and data without degrading performance","Having more developers","Writing longer code"]',1,23),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is a staging environment?','["A theatre stage","A production-like environment used to test changes before they go live","A development database","A backup server"]',1,24),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','Which best describes a responsible AI application?','["One that maximises output speed","One that considers safety, privacy, bias, and user wellbeing in its design","One with the most features","One with no error handling"]',1,25),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is the key benefit of using environment variables for secrets?','["Faster app startup","Secrets are kept out of source code and can be changed without redeploying","Smaller bundle size","Better UI performance"]',1,26),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','In a multi-agent system, what is a subagent?','["A junior developer","A specialised agent that handles a specific task delegated by the orchestrator","A database replica","A test environment"]',1,27),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What is a deployment pipeline?','["A plumbing system","An automated workflow that builds, tests, and deploys code to production","A project Gantt chart","A networking cable"]',1,28),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What makes a good capstone project portfolio piece?','["The most complex code","A real problem solved, clear documentation, live demo, and measurable results","The longest README","The most dependencies"]',1,29),
('9387dab1-4eab-4f7c-ada7-c649abd89a16','cert4-final-exam','What distinguishes a Certified AI Application Developer?','["Knowing one framework","The ability to design, build, deploy, and maintain AI-powered applications professionally","Writing the most code","Having the highest GPA"]',1,30);
